# <div align=center>Numpy</div>   #

In [1]:
import numpy as np

Print the Numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

Create a null vector of size 10


In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value is 1

In [4]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [5]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Reverse a vector

In [6]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Create a 3X3 matrix with values ranging from 0 to 8

In [7]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


Create a 3X3 identity matrix

In [9]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3X3X3 array with random values

In [10]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.10453313 0.17423057 0.16017424]
  [0.15535226 0.4470757  0.60911915]
  [0.24842622 0.69244237 0.77979757]]

 [[0.41413436 0.32421559 0.02944305]
  [0.28483165 0.91027381 0.15554424]
  [0.72436462 0.20136419 0.904627  ]]

 [[0.88959635 0.59799326 0.57316644]
  [0.16056142 0.33135312 0.0382893 ]
  [0.95577634 0.1353959  0.70144828]]]


Create a random vector of size 30 and find the mean value 

In [11]:
Z = np.random.random((30))
m = Z.mean()
print(m)

0.4683706875202171


Create a 10X10 array with random values and find the minimum and the maximum value

In [12]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0023972957011879625 0.9988933697239638


Create a 2D array with 1 on the border and zero inside

In [13]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Create a 8X8 matrix and fill it with checkboard pattern

In [14]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Create a 5X5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
Z = np.diag(1 + np.arange(4), k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Consider a (6,7,8) shape array. What is the index (x,y,z) of the 100th element?

In [16]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


Create a checkerboard pattern 8X8 matrix with the use of tile function

In [17]:
Z = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normalize a 5X5 random matrix

In [18]:
Z = np.random.random([5,5])
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.56392127 0.87476295 0.10607537 0.84209953 0.15517483]
 [0.36588472 0.90333982 0.78317741 0.55074746 0.48710777]
 [0.19132228 0.64605144 0.86706966 1.         0.97849127]
 [0.         0.82600333 0.39001488 0.16981075 0.25413057]
 [0.96748757 0.2314717  0.04926514 0.12684371 0.55844885]]


Design a custom dtype that describes a color as four unsigned bytes (RGBA)

In [19]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-19-5432efe93e2f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


Multiply a 5x3 matrix by a 3x2 matrix 

In [20]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Given a 1D array. Negate all elements which are between 3 and 8 (in place)

In [21]:
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


Find output of the code:

In [22]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


Round away from zero a float array

In [23]:
Z = np.random.uniform(-10,+10,10)
print(np.trunc(Z + np.copysign(0.5, Z)))

[-7. -7. -8.  3. 10.  1. -3.  0.  3.  1.]


Extract the integer part of a random array using 5 different methods


In [24]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(np.trunc(Z))

[2. 9. 9. 1. 0. 9. 2. 3. 0. 3.]
[2. 9. 9. 1. 0. 9. 2. 3. 0. 3.]
[2. 9. 9. 1. 0. 9. 2. 3. 0. 3.]
[2 9 9 1 0 9 2 3 0 3]
[2. 9. 9. 1. 0. 9. 2. 3. 0. 3.]


Create a 5X5 matrix with row values ranging from 0 to 4

In [25]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Create a generator function that generates 10 integers and use it to build an array

In [26]:
def generator():
    for x in range(10):
        yield x
Z = np.fromiter(generator(), dtype = float, count = -1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Create a vector of size 10 with values ranging from 0 to 1(both excluded)

In [27]:
Z = linspace(0, 1, 12, endpoint = True )[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Create a random vector of size 10 and then sort it

In [28]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.4687627  0.698083   0.72155759 0.77096697 0.7714722  0.80320329
 0.80478871 0.88507956 0.98245419 0.9994063 ]


To sum a small array faster than np.sum

In [29]:
Z = np.arange(10)
np.add.reduce(Z)

45

Consider two random array A and B. Ckeck if the equal 

In [30]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


Make an array immutable(read only)

In [31]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

Consider a random 10X2 matrix representing cartesian coordinates. Convert them to polar coordinates


In [32]:
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.6255985  0.50781889 0.24188294 0.81840741 0.76083142 1.08353792
 0.79103119 0.89014328 0.25354628 0.84668643]
[1.00232905 1.33314557 0.61103981 0.6028317  1.39469936 0.60501327
 0.08303397 0.78393198 0.07657849 0.04086251]


Create a structured array with x and y coordinates covering the [0,1]X[0,1] area

In [33]:
Z = np.zeros((10,10), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

Create a random vector of size 10 qnd replace the maximum value by 0

In [34]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.38526975 0.         0.49844904 0.09752027 0.61549427 0.42947117
 0.57250544 0.30164744 0.61705541 0.24000796]


Given two arrays X and Y. Construct the Cauchy matrix C(Cij = 1/(xi-yj))

In [35]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


Print the minimum and maximum representable value for each numpy scalar type

In [36]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


How to print all the values of an array

In [39]:
np.set_printoptions()
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

How to find the closest value (to a given scalar) in an array

In [40]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z - v).argmin())
print(Z[index])

16


Create a structured array representing a position (x,y) and a color (r,g,b)

In [41]:
Z = np.zeros(10, [('position', [('x', float, 1),
                                ('y', float, 1)]),
                  ('color',    [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])

print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-41-15b802b0d590>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('position', [('x', float, 1),


Cosider a random vector with shape (100,2) representing coordinates. Find point by point distances.

In [42]:
Z = np.random.random((10,2))
X, Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X - X.T)**2 + (Y - Y.T)**2 )
print(D)

[[0.         0.48347835 1.17354977 0.73494278 0.48134417 1.10129077
  0.07014141 0.76049212 0.87892246 0.75822611]
 [0.48347835 0.         0.81220442 0.75955801 0.34081439 0.74900487
  0.49607605 0.27891501 0.43615    0.79309113]
 [1.17354977 0.81220442 0.         0.78292395 0.70076818 0.07357319
  1.21920182 0.63969789 0.41830408 0.80366884]
 [0.73494278 0.75955801 0.78292395 0.         0.41877673 0.71840047
  0.80414749 0.86692163 0.78867147 0.03403764]
 [0.48134417 0.34081439 0.70076818 0.41877673 0.         0.62748194
  0.53527257 0.48526113 0.4881112  0.45237218]
 [1.10129077 0.74900487 0.07357319 0.71840047 0.62748194 0.
  1.14765003 0.5918994  0.37302466 0.74041504]
 [0.07014141 0.49607605 1.21920182 0.80414749 0.53527257 1.14765003
  0.         0.77498821 0.90808665 0.8277574 ]
 [0.76049212 0.27891501 0.63969789 0.86692163 0.48526113 0.5918994
  0.77498821 0.         0.22157745 0.90062778]
 [0.87892246 0.43615    0.41830408 0.78867147 0.4881112  0.37302466
  0.90808665 0.221577

How to convert a float array(32 bits) into an integer(32 bits) in place?

In [43]:
Z = np.arange(10, dtype = np.float32)
Z = Z.astype(np.int32, copy = False)
print(Z.dtype)

int32



What is equiivalent of a enumerate for numpy arrays?


In [44]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

for index in np.ndindex(Z.shape):
    print(index, Z[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


Generate a generic 2-D Gaussian-like array 

In [45]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D - mu)**2 / (2.0 * sigma**2) ))
print(G)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

How to randomly place p elements in a 2D array?

In [46]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


Subtract the mean of each row of a matrix

In [47]:
X = np.random.rand(5,10)

Y = X - X.mean(axis = 1, keepdims = True)

print(Y)

[[-0.32236071  0.21983249  0.39004226 -0.14787774 -0.23824109  0.19759816
  -0.10906123  0.05847456 -0.17643669  0.12802999]
 [ 0.30849028 -0.13114938  0.18956572  0.15329308  0.13385181 -0.18982586
   0.06937105 -0.25519417 -0.17369759 -0.10470494]
 [-0.4576551  -0.010207   -0.01992422 -0.26904757  0.25330136  0.35808442
  -0.32265899  0.35825925  0.18160125 -0.07175342]
 [-0.34087643 -0.01181918  0.0130744  -0.02865632  0.52545317 -0.21396338
  -0.178273    0.28844536 -0.39665315  0.34326854]
 [-0.31736634  0.08633856  0.12134299  0.33624477 -0.33686159  0.21065839
  -0.4633077   0.1085212  -0.01427896  0.2687087 ]]


How to sort an array by the nth column?

In [48]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 0 8]
 [1 1 5]
 [7 2 6]]
[[1 0 8]
 [1 1 5]
 [7 2 6]]


How to tell the nearest value from a given value in an array

In [49]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.47692242091387393


How to tell if a given 2D array has null columns 

In [50]:
Z = np.random.randint(0,3, (3,10))
print(Z)
print((~Z.any(axis = 0)).any())

[[0 1 2 0 1 2 0 1 0 0]
 [0 0 2 2 2 2 0 1 1 2]
 [0 2 2 2 2 2 1 1 0 1]]
True


Create an array class that has a name attribute

In [51]:
class NamedArray(np.ndarray):
    
    def __new__(cls, array, name = "no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
    
Z = NamedArray(np.arange(10), "range_10")
print(Z.name)


range_10


Consider a given vector. How to add 1 to each element indexed by a second vector (Be careful with repeated indices)

In [52]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength = len(Z))
print(Z)

[2. 5. 1. 2. 5. 4. 2. 4. 3. 2.]


How to accumulate elements of a vector(X) to an array (F) based on an index list(I)?

In [53]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


Considering a (w,h,3) image of (dtype = ubyte), compute the number of unique colors

In [54]:
w, h = 16, 16
I = np.random.randint(0.2, (h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 + I[...,2]
n = len(np.unique(F))
print(np.unique(F))

[659202]


Considering a one-dimensional vector D, compute means of subsets of D using a vector S of same size describing subset indices?

In [55]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,1,100)
D_sums = np.bincount(S, weights = D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.45308148]


How to get the diagonal of a dot product?

In [56]:
A = np.arange(6).reshape(3,2)
B = np.arange(6).reshape(2,3)

np.diag(np.dot(A, B))

array([ 3, 14, 33])

Consider an array of dimension (5,5,3), multiply it with an array with dimensions (5,5)

In [57]:
A = np.ones((5,5,3))
B = 2 * np.ones((5,5))

print(A * B[:,:, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


How to swap two rows of an array?

In [58]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing of all the triangles


In [59]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis = 1),-1,axis = 1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis = 1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 83) ( 1, 84) ( 3, 91) ( 3, 97) ( 4, 17) ( 4, 65) ( 6,  8) ( 6, 92)
 ( 8, 16) ( 8, 34) ( 8, 37) ( 8, 48) ( 8, 92) ( 9, 41) ( 9, 88) (13, 41)
 (13, 65) (16, 34) (17, 65) (19, 46) (19, 79) (22, 24) (22, 60) (24, 60)
 (37, 48) (41, 65) (41, 88) (46, 79) (83, 84) (91, 97)]


Given an array C that is a bincount, produce an array A such that np.bicount(A) == C

In [60]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


How to calculate averages using a sliding window over an array?

In [61]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


Consider a one dimensional array Z, build a two dimensional array whose first
row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should
be (Z[3],Z[2],Z[1])

In [62]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


How to negate a boolean, or to change the sign of a float inplace?


In [63]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out = Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out = Z)

array([-0.04188511,  0.42734728,  0.62513311,  0.72959967, -0.5808537 ,
        0.02203452,  0.07939833,  0.7566196 , -0.55389804, -0.56018925,
        0.48741304,  0.01298041,  0.26952026,  0.48273486,  0.97051176,
        0.90128746, -0.53425886,  0.0867439 , -0.75188382, -0.87489757,
       -0.60455632, -0.98198778,  0.58970067, -0.39696103,  0.94430911,
        0.37676432, -0.3388234 ,  0.36307482,  0.06253821, -0.18128882,
        0.77306544,  0.97160743, -0.71914259,  0.45834852,  0.54060496,
        0.2364726 ,  0.81002279, -0.25297408,  0.46572962, -0.93519246,
        0.03962513,  0.67733404, -0.07600253, -0.80800122, -0.65492934,
       -0.92402801, -0.21031981,  0.57570278,  0.44864402, -0.4975353 ,
       -0.6355743 ,  0.09312313, -0.40603386, -0.40165873, -0.79297014,
        0.6871292 , -0.28706242,  0.17594958,  0.52337662, -0.19995289,
       -0.41135343, -0.63375351, -0.57554554, -0.87459645,  0.94860076,
       -0.14519857, -0.44421978, -0.50493739,  0.5231199 ,  0.40

Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to
compute distance from p to each line i (P0[i],P1[i])?

In [64]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[14.55426828  4.31694537 11.14851558  7.86804946  3.90186064  0.47519983
  7.43481567  7.52757909  9.27733719  9.72339103]


Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [65]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.17554666  2.27498612  2.95166279  2.11871669  1.40188954  8.4800519
  13.75832336  3.33786725  6.03769785  2.03785767]
 [ 0.20892451  0.11665394  0.4215341   2.64774769  2.38862842  5.39306031
   9.63774482  0.73651815  5.39994145  0.15190771]
 [ 5.5951092   5.27960216  6.94596697 10.43746849  3.82546546  2.25612558
  12.0529927   0.94920811  2.27557984  5.7580096 ]
 [ 4.10637516  1.34206348  4.38891331  2.31460464  6.62630521  2.81742976
   5.49458396  4.7582103   5.61837287  0.99512628]
 [ 2.05137248 13.73329855  1.88035819 15.84370561  2.9314181   7.47306189
   2.47025415  8.88825713  7.90864593 13.76077045]
 [ 8.62163365  4.55239448  9.82750502 10.97341121  6.83546133  3.8021478
  14.84580237  3.63313458  2.73225784  5.25450955]
 [ 0.35888307  3.86406297  1.06567833  6.7783972   1.72477565  1.934478
   8.24217169  2.4591332   1.25709053  3.90925904]
 [ 0.90210083  6.81103511  0.75006504  9.2565796   2.64006813  1.03666379
   6.06885518  4.79880509  1.2647337   6.80868387]
 [ 1

Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fillvalue when necessary)

In [66]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]

R[r] = Z[z]

print(Z)
print(R)

[[6 6 5 9 0 4 7 6 0 5]
 [9 4 5 4 7 6 4 5 2 0]
 [8 8 3 1 0 9 6 6 4 1]
 [7 6 8 0 5 8 9 3 4 9]
 [7 9 9 6 0 3 9 4 1 5]
 [1 9 9 8 1 4 0 5 4 4]
 [3 1 1 7 8 1 6 7 5 0]
 [3 7 3 4 8 1 8 1 6 3]
 [4 0 7 3 8 7 8 8 2 5]
 [5 5 0 4 9 7 9 0 1 8]]
[[0 0 0 0 0]
 [0 6 6 5 9]
 [0 9 4 5 4]
 [0 8 8 3 1]
 [0 7 6 8 0]]


<ipython-input-66-79134c150b40>:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [67]:
Z = np.arange(1,15,dtype=uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


Compute a matrix rank

In [68]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


How to find the most frequent value in an array?


In [69]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [70]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 3 4]
   [3 0 4]
   [3 1 3]]

  [[3 4 1]
   [0 4 1]
   [1 3 3]]

  [[4 1 4]
   [4 1 2]
   [3 3 4]]

  [[1 4 1]
   [1 2 1]
   [3 4 1]]

  [[4 1 3]
   [2 1 2]
   [4 1 1]]

  [[1 3 1]
   [1 2 2]
   [1 1 4]]

  [[3 1 0]
   [2 2 4]
   [1 4 2]]

  [[1 0 0]
   [2 4 4]
   [4 2 3]]]


 [[[3 0 4]
   [3 1 3]
   [2 1 4]]

  [[0 4 1]
   [1 3 3]
   [1 4 1]]

  [[4 1 2]
   [3 3 4]
   [4 1 1]]

  [[1 2 1]
   [3 4 1]
   [1 1 2]]

  [[2 1 2]
   [4 1 1]
   [1 2 3]]

  [[1 2 2]
   [1 1 4]
   [2 3 0]]

  [[2 2 4]
   [1 4 2]
   [3 0 3]]

  [[2 4 4]
   [4 2 3]
   [0 3 4]]]


 [[[3 1 3]
   [2 1 4]
   [0 0 3]]

  [[1 3 3]
   [1 4 1]
   [0 3 0]]

  [[3 3 4]
   [4 1 1]
   [3 0 4]]

  [[3 4 1]
   [1 1 2]
   [0 4 3]]

  [[4 1 1]
   [1 2 3]
   [4 3 3]]

  [[1 1 4]
   [2 3 0]
   [3 3 4]]

  [[1 4 2]
   [3 0 3]
   [3 4 2]]

  [[4 2 3]
   [0 3 4]
   [4 2 0]]]


 [[[2 1 4]
   [0 0 3]
   [0 0 4]]

  [[1 4 1]
   [0 3 0]
   [0 4 2]]

  [[4 1 1]
   [3 0 4]
   [4 2 4]]

  [[1 1 2]
   [0 4 3]
   [2 4 1]]

  [[1 2 3]
   

Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [71]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42

print(S)

[[ 6 11 14  3  5]
 [11  1 14 13  6]
 [14 14  5 42 16]
 [ 3 13 42  8  6]
 [ 5  6 16  6  1]]


Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has
shape (n,1)) 

In [72]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


Consider a 16x16 array, how to get the block­sum (block size is 4x4)?

In [73]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


How to implement the Game of Life using numpy arrays? 

In [74]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2: , 1:-1] + Z[2: , 2:])

    birth = (N == 3) & (Z[1:-1,1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


 How to get the n largest values of an array?

In [75]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [76]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


How to create a record array from a regular array? 

In [77]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])

R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [78]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 4 6 7]


 Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [79]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[0 1 0]
 [0 4 1]
 [2 1 1]
 [0 0 0]
 [1 1 2]
 [3 4 3]
 [1 2 1]
 [2 2 3]
 [3 0 4]
 [4 3 4]]
[[0 1 0]
 [0 4 1]
 [2 1 1]
 [1 1 2]
 [3 4 3]
 [1 2 1]
 [2 2 3]
 [3 0 4]
 [4 3 4]]


Convert a vector of ints into a matrix binary representation

In [80]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Given a two dimensional array, how to extract unique rows?

In [81]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1]))) 
_, idx = np.unique(T, return_index = True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [82]:
A = np.arange(0,10)
B = np.arange(0,10)

np.einsum('i->', A) 
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B) 
np.einsum('i,j', A, B) 

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [83]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)*2 + np.diff(y)*2) * 0.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x) 
y_int = np.interp(r_int, r, y)

Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [84]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]
